return {
    CUSTOMER = {
        HAT = {
            3403874988, -- The Encierro Cap
            63689493, -- Hunter Snow Cap
            6837506, -- Tin Pot
            73806172412277 -- Roblox Learn Plumera Crown
        },

        HAIR = {
            451221329, -- True Blue Hair
            63690008, -- Pal Hair
            1103003368, -- Orange Beanie with Black Hair
            2956239660 -- Belle Of Belfast Long Red Hair
        },

        SHIRT = {
            398633584, -- Denim Jacket with White Hoodie
            3670737444, -- Roblox Shirt - Simple Pattern
            398634295, -- Pastel Starburst Top with Gray Jacket
            398635081 -- Blue Plaid Shirt 
        },

        PANTS = {
            382537806, -- Jean Shorts
            398633812, -- Black Jeans with White Shoes
            398634487, -- Beautiful You Jeans
            398635338 -- Ripped Skater Pants
        }
    }
}