name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.4.2
              with:
                token: ${{ github.token }}

            - name: Install Dependencies
              run: wally install
            
            - name: Check Formatting
              run: stylua --check src/
            
            - name: Lint Code
              run: selene src/
