name: Deploy To Production

on:
    push:
        tags:
        - 'v*'
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.4.2
              with:
                token: ${{ github.token }}

            - name: Publish place
              shell: bash
              env:
                UID: 8152024688
                PID: 103691878268796
                API_KEY: ${{ secrets.API_KEY }}
                FILE: build.rbxl
              run: rbxcloud experience publish -a "$API_KEY" -u "$UID" -p "$PID" -t published -f "$FILE"