name: Deploy To Production

on:
    push:
        tags:
        - 'v*'
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            
            - name: Setup Aftman
              uses: ok-nick/setup-aftman@v0.4.2
              with:
                token: ${{ github.token }}

            - name: Build place
              run: rojo build -o build.rbxl

            - name: Publish place
              shell: bash
              env:
                UID: 8152024688
                PID: 103691878268796
                API_KEY: ${{ secrets.API_KEY }}
                FILE: build.rbxl
              run: rbxcloud experience publish --filename $FILE --place-id $PID --universe-id $UID --version-type published --api-key $API_KEY